### ISSUE TITLE
aar in releases not updated

### ISSUE THREAD

**Issue by YmlMark** [7digital/7digital-Android-SDK#15] opened 2015-10-05 23:00 UTC
Bug fix not available in pre built aar.

**Comment by juliusspencer** [comment] 2015-10-06 02:36
Hi Mark,
That should be available now. Let me know if you have any further issues; I'll leave this open for a while.

**Comment by YmlMark** [comment] 2015-10-06 14:52
Thanks for being responsive. Have you considered making this aar available via jcenter/maven central, or your own repo?

**Comment by juliusspencer** [comment] 2015-10-06 18:43
That's a great idea.

**Comment by YmlMark** [comment] 2015-10-06 19:21
BTW, I'm not super clear on the dependencies issue. I ended up using your
jar without the built in dependencies. Had Jackson conflict issues, so
deleted the explicit Jackson dependencies. Not yet at the point where I can
confirm that it all works at runtime.

**Comment by YmlMark** [comment] 2015-10-08 00:45
Hi Julius,

I am having runtime, class not found, or duplicate symbol issues because of
all of the dependencies your Android SDK has. OKHttp and Jackson are
problems because they are already in my project. I've tried the jar with
dependencies and without. Same issues.

Is there a vanilla public web service API that serves up JSON that I can
use directly? I already have REST infrastructure set up.

Thanks,

Mark

**Comment by juliusspencer** [comment] 2015-10-08 00:48
Hi Mark,

Can you post the errors you're getting here?

**Comment by YmlMark** [comment] 2015-10-08 00:57
Hi Julius,

Here's an example:

:app:compileDevDebugJava UP-TO-DATE
:app:preDexDevDebug UP-TO-DATE
:app:dexDevDebug UP-TO-DATE
:app:processDevDebugJavaRes UP-TO-DATE
:app:validateDebugSigning
:app:packageDevDebug
Error: duplicate files during packaging of APK
/Users/mark.rosenberg/AndroidStudioProjects/StubHub/app/build/outputs/apk/app-dev-debug-unaligned.apk
Path in archive: res/anim/abc_slide_in_bottom.xml
Origin 1:
/Users/mark.rosenberg/AndroidStudioProjects/StubHub/app/build/intermediates/res/resources-dev-debug.ap_
Origin 2:
/Users/mark.rosenberg/AndroidStudioProjects/StubHub/app/libs/7digital-android-sdk-v0.94-withDependencies.jar
You can ignore those files in your build.gradle:
android {
 packagingOptions {
   exclude 'res/anim/abc_slide_in_bottom.xml'
 }
}

 FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':app:packageDevDebug'.
  > Duplicate files copied in APK res/anim/abc_slide_in_bottom.xml
  File 1:
  /Users/mark.rosenberg/AndroidStudioProjects/StubHub/app/build/intermediates/res/resources-dev-debug.ap_
  File 2:
  /Users/mark.rosenberg/AndroidStudioProjects/StubHub/app/build/intermediates/res/resources-dev-debug.ap_

I can do as suggested, and then it complains about another file. Seems
endless.

I really would prefer at this point just to directly hit the endpoints that
your API is using under the hood and do the json parsing myself. Already
doing it for other web services.

Thanks for your help,

Mark

**Comment by juliusspencer** [comment] 2015-10-08 01:23
Hi Mark,

It appears that there is a duplicate of resource files (from the looks of it the Compat library - appcompat-v7). You will need to exclude those libraries where you have duplicates. eg.

```
compile (project(':sdk')) {
  exclude group: 'com.android.support' module: 'appcompat-v7' 
}
```

The source files in the sdk will show you which libraries are already used.

I can't help you with your question about going directly to the API; you can talk to 7digital about that.

**Comment by YmlMark** [comment] 2015-10-08 17:24
Hi Julius,

Still having issue, but they have changed. Not sure what ended up being
diffferent, but my duplicate/missing class problems are now gone with:

compile files('libs/7digital-android-sdk-v0.94.jar')
        compile('org.simpleframework:simple-xml:2.7.1') {
            exclude module: 'stax'
            exclude module: 'stax-api'
            exclude module: 'xpp3'
        }
        //    compile 'com.mcxiaoke.volley:library:1.0.15'
        compile 'joda-time:joda-time:2.7'
        compile 'com.fasterxml.jackson.core:jackson-core:2.6.2'
        compile 'com.fasterxml.jackson.core:jackson-databind:2.6.2'

My app is already using Retrofit and Picasso, I don't want to use Volley. I
used the SDIApi constructor that only takes app context and Oauth consumer.
However, it looks like Volley is not optional.

In the class SDIArtistSearchRequest, there is no
SDIArtistSearchRequest.Result execute() method that doesn't take a request
queue. So I naturally get:

10-08 10:09:58.870 30040-30246/com.stubhub.music.android
E/com.stubhub.music.android.player.SevenDigitalAPI: requestPreviewTracks()
failed: uk.co.sevendigital.android.sdk.util.OkHttpStack

which originates from

queue = SDICore.getQueue(context);

I was hoping that I could use the API without Volley, and just rely on it
to synchronously make the HTTP request and parse the JSON.

Looking forward to your thoughts,

Mark

**Comment by YmlMark** [comment] 2015-10-08 21:17
Hi Julius,

I gave in and am now using the SDK with Volley. I was getting some
predictable results, but now it looks like server problems:

0-08 14:13:31.988 2650-3011/com.stubhub.music.android E/Volley: [7274]
BasicNetwork.performRequest: Unexpected response code 404 for
http://previews.7digital.com/clip/45936019?country=GB&oauth_consumer_key=7dgnbdspqy4r&oauth_nonce=2685051394659273817&oauth_signature=FBXCKqDzH11991u7YyLVAKs0%2Bgg%3D&oauth_signature_method=HMAC-SHA1&oauth_timestamp=1444338804
10-08 14:13:31.995 2650-2968/com.stubhub.music.android
E/com.stubhub.music.android.player.SevenDigitalAPI: requestPreviewTracks()
failed: com.android.volley.ServerError

Regards,

Mark

**Comment by juliusspencer** [comment] 2015-10-08 23:40
Hi Mark,

There are some tracks in the 7digital catalogue that don’t have preview clips, but most of the time there will be. Are you finding this with every clip?

**Closed** 2015-11-12 17:31 UTC
